# Generated by Django 4.0 on 2023-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dep',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='dep',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
