# Generated by Django 4.0 on 2023-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_course_dep_question_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='dep',
            field=models.IntegerField(null=True),
        ),
    ]
