# Generated by Django 4.0 on 2023-03-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam', '0007_alter_course_dep_alter_question_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='adby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
