# Generated by Django 4.0 on 2023-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_adby'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='examid',
            field=models.IntegerField(null=True),
        ),
    ]
