# Generated by Django 4.0 on 2023-03-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_departiment_alter_course_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departiment',
            name='head',
            field=models.IntegerField(null=True),
        ),
    ]
