# Generated by Django 4.0 on 2023-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_departiment_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
