# Generated by Django 4.0 on 2023-03-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_collage'),
    ]

    operations = [
        migrations.AddField(
            model_name='departiment',
            name='cl_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.collage'),
        ),
    ]
