# Generated by Django 4.0 on 2023-03-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_departiment_cl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.departiment'),
        ),
    ]
