# Generated by Django 4.0 on 2023-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_course_teacher_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='depart',
            field=models.CharField(choices=[('1', 'Computer Science'), ('3', 'Natural Resource Management'), ('4', 'Agri-business and value chain management'), ('5', 'Animal Scince'), ('6', 'Plant Science'), ('7', 'Horticulture'), ('8', 'Veterinary Science'), (' 9', ' Chemistry'), ('10', 'Biology'), ('11', 'Mathematics'), ('12', 'Statics'), ('13', 'Agricultural Economics'), ('14', 'Physics'), ('15', 'Accounting and finance'), ('16', 'management'), ('17', 'Economics'), ('18', 'Veterinary Medicine'), ('19', 'Turism and Hotel Management'), ('20', 'psychology'), ('19', 'Turism and Hotel Management'), ('20', 'psychology'), ('21', 'Geograpy'), ('22', 'Civic'), ('23', 'Social Anthrophology'), ('24', 'History And Heritage management'), ('25', ' English Languege'), ('26', 'Law'), ('27', 'Midwifery'), ('20', 'Nursing'), ('20', 'Public Health')], max_length=255, null=True),
        ),
    ]
