# Generated by Django 4.0 on 2023-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('dat', models.DateField(null=True)),
                ('dur', models.IntegerField(null=True)),
                ('adby', models.IntegerField(null=True)),
            ],
        ),
    ]
