# Generated by Django 4.0 on 2023-03-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teacher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tim',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
