# Generated by Django 4.1.4 on 2022-12-22 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('date', models.DateField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('employee', 'employee'), ('visitor', 'visitor')], default='employee', max_length=20, null=True)),
                ('present', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shift', models.TimeField(null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('age', models.DateField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('exp', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('gfrom', models.CharField(max_length=255, null=True)),
                ('gyear', models.DateField(null=True)),
                ('bimage', models.ImageField(null=True, upload_to='image')),
                ('certicate', models.ImageField(null=True, upload_to='certificate')),
                ('valid', models.BooleanField(default=True)),
                ('bcmgpa', models.IntegerField(null=True)),
                ('bach', models.DateField(null=True)),
                ('msc', models.DateField(null=True)),
                ('phd', models.DateField(null=True)),
                ('mimage', models.ImageField(null=True, upload_to='certificate')),
                ('pimage', models.ImageField(null=True, upload_to='certificate')),
                ('mcmgpa', models.IntegerField(null=True)),
                ('pcmgpa', models.IntegerField(null=True)),
                ('dt', models.DateField(auto_now=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LastFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_face', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
