# Generated by Django 4.1.4 on 2022-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_age_remove_profile_certicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certicate',
            field=models.ImageField(null=True, upload_to='certificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='fn', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='ln', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shift',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('visitor', 'visitor')], default='employee', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
