# Generated by Django 4.1.4 on 2022-12-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lastface_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regby',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
