# Generated by Django 4.1.4 on 2022-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_regby_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='regby',
            field=models.BigIntegerField(null=True),
        ),
    ]
