# Generated by Django 4.1.4 on 2022-12-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_regby'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adby',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
