# Generated by Django 4.0 on 2023-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dep',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
