# Generated by Django 4.0 on 2023-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regby',
            field=models.IntegerField(null=True),
        ),
    ]
